### ISSUE TITLE
글쓰기 화면 기능 개발

### ISSUE THREAD

**Issue by CharmingCheol** [Double-Slash/5th-final-team1-web#10]
# Page

- pages/write

# Components

- 컴포넌트의 이름과 해당 이슈 번호들을 체크박스로 적어주세요
- ex) -[ ] #1 [Main] 메인 페이지 작성
- [x] #34 MarkdownEditor 컴포넌트 추가
- [x] #35 EditorToolbar 컴포넌트 추가
- [ ] #40 EditorPreview 컴포넌트
- [ ] #43 Write/TitleInput 컴포넌트 생성
- [ ] #44 Write/MarkDownEditor 리팩토링

# Explanation
- ckeditor나 monaco editor 라이브러리 대신, codemirror와 prismjs를 조합하여 마크다운 에디터 구성. codemirror와 prismjs을 사용하는 방법으로 하는게 bundle size가 훨씬 적음
  - monaco : 2.3MB
  - ckeditor : 622.4kB
  - codemirror : 168kB
  - prismjs : 16.1KB
- 디자인 시안이 나오기 전 아래와 같은 동작을 미리 개발
  - 텍스트 -> 마크다운 인식(codemirror) -> 마크다운 텍스트를 마크다운으로 랜더링(prismjs)
  - 에디터 툴바 버튼 동작(헤딩, 볼드, 이탤릭, 스트라이크, 코드 삽입)
  - 입력한 코드 인식

**Comment by CharmingCheol** [comment]
마크다운 랜더링 컴포넌트 추가로 인해 이슈 리오픈
